version: 0.0  # CodeDeploy 버전
os: linux
files:
  - source: / # CodeDeploy 로부터 전달받은 파일 중 destination 으로 이동시킬 대상 지정
    destination: /home/ubuntu/app/zip/ # source 에서 지정된 파일을 받을 위치
    overwrite: yes  # 기존에 있는 파일에 덮어쓰기

# CodeDeploy에서 EC2 서버로 넘겨준 파일들이 모두 ubnutu 권한을 가지도록 설정
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

# CodeDeploy 배포 단계에서 실행할 명령어 지정
hooks:
  ApplicationStart:   # deploy.sh를 ubuntu 권한으로 실행
    - location: deploy.sh
      timeout: 60     # 스크립트가 60초 이상 수행될 경우 실패
      runas: ubuntu