version: 0.0  # CodeDeploy 버전
os: linux
files:
  - source: /   # CodeDeploy에서 전체 파일을 전달 받아 destination으로 이동
    destination: /home/ubuntu/app/zip/  # source에서 지정된 파일을 받을 위치
    overwrite: yes  # 기존 파일들에 덮어쓰기
# test