version: 0.0  # CodeDeploy 버전
os: linux
files:
  - source: / # CodeDeploy 로부터 전달받은 파일 중 destination 으로 이동시킬 대상 지정
    destination: /home/ubuntu/app/zip # source 에서 지정된 파일을 받을 위치
    overwrite: yes  # 기존에 있는 파일에 덮어쓰기
